language: node_js
node_js:
  - "0.12"
services:
  - rabbitmq
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database fire;' -U postgres
  - psql -d fire -c 'create extension "uuid-ossp";' -U postgres
env:
  - DATABASE_URL=postgres://postgres@localhost/fire BROKER_URL=amqp://localhost DEBUG=fire:* NODE_APP=default WEB_SOCKET_PORT=8765
